export enum EnvVarEnum {
	NODE_ENV = "NODE_ENV",

	PORT = "PORT",

	JWT_SECRET = "JWT_SECRET",
	JWT_EXPIRATION_TIME = "JWT_EXPIRATION_TIME",
	COOKIE_EXPIRATION_TIME = "COOKIE_EXPIRATION_TIME",

	DB_URL = "DB_URL",
	DB_LOGGING = "DB_LOGGING"
}
