export enum EnvVarEnum {
	NODE_ENV = "NODE_ENV",

	PORT = "PORT",

	JWT_SECRET = "JWT_SECRET",
	JWT_EXPIRATION_TIME = "JWT_EXPIRATION_TIME",
	COOKIE_EXPIRATION_TIME = "COOKIE_EXPIRATION_TIME",

	GOOGLE_CLIENT_ID = "GOOGLE_CLIENT_ID",
	GOOGLE_CLIENT_SECRET = "GOOGLE_CLIENT_SECRET",
	GOOGLE_CALLBACK_URL = "GOOGLE_CALLBACK_URL",

	DB_URL = "DB_URL",
	DB_LOGGING = "DB_LOGGING",

	SENDGRID_API_KEY = "SENDGRID_API_KEY",
	SENDGRID_SENDER_ID = "SENDGRID_SENDER_ID"
}
