export enum ProblemTypeEnum {
	UNIQUE_CONSTRAINT = "UNIQUE_CONSTRAINT",
	ENTITY_NOT_FOUND = "ENTITY_NOT_FOUND",
	ENTITY_IN_USE = "ENTITY_IN_USE",
	BUSINESS_EXCEPTION = "BUSINESS_EXCEPTION",
	HTTP_EXCEPTION = "HTTP_EXCEPTION"
}
